(function () {
  "use strict";

  var app = document.getElementById("hr-app");
  var shell = document.querySelector(".hr-shell");
  var gate = document.getElementById("security-gate");
  var title = document.getElementById("page-title");
  var actions = document.getElementById("top-actions");
  var csrf = "";
  var state = { dashboard: null, employees: [], total: 0, employee: null, audit: [], tab: "profile" };
  var toastTimer;

  function esc(value) { return String(value == null ? "" : value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;"); }
  function date(value) { if (!value) return "-"; var p=String(value).slice(0,10).split("-"); return p.length===3?p[2]+"-"+p[1]+"-"+p[0]:value; }
  function toast(message) { var el=document.getElementById("hr-toast"); el.textContent=message; el.classList.add("visible"); clearTimeout(toastTimer); toastTimer=setTimeout(function(){el.classList.remove("visible");},3000); }
  function api(path, options) {
    options=options||{}; var headers=Object.assign({},options.headers||{}); var body=options.body;
    if (body && !(body instanceof FormData)) { headers["Content-Type"]="application/json"; body=JSON.stringify(body); }
    if (["POST","PUT","PATCH","DELETE"].indexOf(String(options.method||"GET").toUpperCase())>=0) headers["X-CSRF-Token"]=csrf;
    return fetch(path,Object.assign({credentials:"same-origin"},options,{headers:headers,body:body})).then(function(response){
      if (options.binary && response.ok) return response.blob();
      return response.text().then(function(text){ var payload={}; try{payload=text?JSON.parse(text):{};}catch(_e){} if(!response.ok){var err=new Error(payload.error||"Verzoek mislukt.");err.status=response.status;err.code=payload.code;throw err;}return payload;});
    });
  }
  function route() { return (location.hash||"#dashboard").slice(1); }
  function navigate(value) { location.hash="#"+value; }
  function showGate(html) { shell.hidden=true; gate.hidden=false; gate.innerHTML='<div class="gate-card">'+html+'</div>'; }
  function showApp() { gate.hidden=true; shell.hidden=false; }

  function setupGate() {
    showGate('<p class="eyebrow">Eenmalige inrichting</p><h1>Authenticator instellen</h1><p class="muted">Bevestig eerst uw beheerderswachtwoord. Daarna koppelt u Google Authenticator, Microsoft Authenticator of een vergelijkbare app.</p><form data-form="mfa-start"><label class="field">Huidig wachtwoord<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">Verder</button></form><p><a href="/">Terug naar CRM</a></p>');
  }
  function setupConfirm(payload) {
    showGate('<p class="eyebrow">Authenticator koppelen</p><h1>Scan de QR-code</h1><img class="qr" alt="QR-code voor authenticator" src="'+esc(payload.qrCode)+'"><div class="notice">Handmatige sleutel: <strong>'+esc(payload.secret)+'</strong></div><form data-form="mfa-confirm"><label class="field">6-cijferige code<input name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required></label><button class="primary">Activeren</button></form>');
  }
  function recoveryGate(codes) {
    showGate('<p class="eyebrow">Belangrijk</p><h1>Bewaar uw herstelcodes</h1><p>Iedere code werkt één keer. Bewaar ze offline in een wachtwoordmanager; ze worden hierna niet opnieuw getoond.</p><div class="notice"><code>'+codes.map(esc).join("<br>")+'</code></div><button class="primary" data-action="recovery-finished">Ik heb ze veilig opgeslagen</button>');
  }
  function elevateGate() {
    showGate('<p class="eyebrow">Extra verificatie</p><h1>Werknemersportaal openen</h1><p class="muted">Voer uw wachtwoord en authenticatorcode in. Een eenmalige herstelcode mag ook.</p><form data-form="elevate"><label class="field">Wachtwoord<input name="password" type="password" autocomplete="current-password" required></label><label class="field">Authenticator- of herstelcode<input name="code" autocomplete="one-time-code" required></label><button class="primary">Veilig openen</button></form><p><a href="/">Terug naar CRM</a></p>');
  }

  function employeeStatus(value) { return ({active:"Actief",leave:"Verlof",ended:"Uit dienst",archived:"Archief"})[value]||value; }
  function employmentType(value) { return ({permanent:"Vast",temporary:"Tijdelijk",on_call:"Oproep",contractor:"Inhuur",intern:"Stage"})[value]||value; }
  function statusPill(value) { var tone=value==="active"?"ok":value==="archived"?"danger":"warn"; return '<span class="pill '+tone+'">'+esc(employeeStatus(value))+'</span>'; }
  function metric(label,value) { return '<article class="card metric"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong></article>'; }
  function renderDashboard() {
    title.textContent="Dashboard"; actions.innerHTML='<button class="primary" data-action="employee-new">Nieuwe werknemer</button>';
    var d=state.dashboard||{active:0,archived:0,missingContracts:0,expiring30:0,expiring60:0,expiring90:0,expiring:[]};
    var rows=d.expiring.length?d.expiring.map(function(item){var days=Math.ceil((new Date(item.endDate+"T00:00:00")-new Date())/86400000);return '<tr data-open="employee:'+esc(item.employee.id)+'"><td><strong>'+esc(item.employee.firstName+" "+item.employee.lastName)+'</strong><br><span class="muted">'+esc(item.employee.employeeNumber)+'</span></td><td>'+esc(item.title)+'</td><td>'+date(item.endDate)+'</td><td><span class="pill warn">'+esc(Math.max(0,days))+' dagen</span></td></tr>';}).join(""):'<tr><td colspan="4"><div class="empty">Geen contracten die binnen 90 dagen verlopen.</div></td></tr>';
    app.innerHTML='<section class="grid metrics">'+metric("Actieve werknemers",d.active)+metric("Uit dienst / archief",d.archived)+metric("Zonder actief contract",d.missingContracts)+metric("Verloopt ≤ 30 dagen",d.expiring30)+metric("Verloopt ≤ 60 dagen",d.expiring60)+metric("Verloopt ≤ 90 dagen",d.expiring90)+'</section><section class="card" style="margin-top:18px"><div class="panel-head"><div><p class="eyebrow">Contractbewaking</p><h2>Binnenkort verlopend</h2></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Werknemer</th><th>Contract</th><th>Einddatum</th><th>Termijn</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>';
  }
  function renderEmployees() {
    title.textContent="Werknemers"; actions.innerHTML='<button class="primary" data-action="employee-new">Nieuwe werknemer</button>';
    var rows=state.employees.length?state.employees.map(function(e){return '<tr data-open="employee:'+esc(e.id)+'"><td><strong>'+esc(e.displayName)+'</strong><br><span class="muted">'+esc(e.employeeNumber)+'</span></td><td>'+esc(e.jobTitle||"-")+'</td><td>'+esc(e.department||"-")+'</td><td>'+statusPill(e.status)+'</td><td>'+date(e.endDate)+'</td><td>'+esc(e.contractCount||0)+'</td></tr>';}).join(""):'<tr><td colspan="6"><div class="empty">Geen werknemers gevonden.</div></td></tr>';
    app.innerHTML='<section class="card"><div class="filters"><input aria-label="Zoeken" data-filter="search" placeholder="Naam of nummer"><input aria-label="Afdeling" data-filter="department" placeholder="Afdeling"><input aria-label="Functie" data-filter="jobTitle" placeholder="Functie"><select aria-label="Status" data-filter="status"><option value="">Alle statussen</option><option value="active">Actief</option><option value="leave">Verlof</option><option value="ended">Uit dienst</option><option value="archived">Archief</option></select><label class="field">Contract eindigt vóór<input type="date" data-filter="contractEndBefore"></label><button data-action="employee-filter-all">Filter</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Werknemer</th><th>Functie</th><th>Afdeling</th><th>Status</th><th>Einddatum</th><th>Contracten</th></tr></thead><tbody>'+rows+'</tbody></table></div><p class="muted">'+esc(state.total)+' dossier(s)</p></section>';
  }
  function options(values,selected) { return values.map(function(x){return '<option value="'+x[0]+'"'+(x[0]===selected?' selected':'')+'>'+esc(x[1])+'</option>';}).join(""); }
  function employeeForm(employee) {
    var e=employee||{}; title.textContent=e.id?"Werknemer bewerken":"Nieuwe werknemer"; actions.innerHTML="";
    app.innerHTML='<form class="card" data-form="employee" data-id="'+esc(e.id||"")+'"><div class="panel-head"><div><p class="eyebrow">Personeelsdossier</p><h2>'+ (e.id?"Gegevens wijzigen":"Werknemer toevoegen") +'</h2></div><div class="button-row"><button type="button" data-action="cancel-employee">Annuleren</button><button class="primary">Opslaan</button></div></div><div class="field-grid">'+
      field("Personeelsnummer","employeeNumber",e.employeeNumber,true)+field("Voornaam","firstName",e.firstName,true)+field("Achternaam","lastName",e.lastName,true)+field("Werk-e-mail","workEmail",e.workEmail,false,"email")+field("Werktelefoon","workPhone",e.workPhone)+field("Functie","jobTitle",e.jobTitle)+field("Afdeling","department",e.department)+
      '<label class="field">Status<select name="status">'+options([["active","Actief"],["leave","Verlof"],["ended","Uit dienst"],["archived","Archief"]],e.status||"active")+'</select></label><label class="field">Dienstverband<select name="employmentType">'+options([["permanent","Vast"],["temporary","Tijdelijk"],["on_call","Oproep"],["contractor","Inhuur"],["intern","Stage"]],e.employmentType||"permanent")+'</select></label>'+field("Uren per week","hoursPerWeek",e.hoursPerWeek,false,"number",' min="0" max="80" step="0.5"')+field("Startdatum","startDate",e.startDate,true,"date")+field("Einddatum","endDate",e.endDate,false,"date")+
      '<div class="field full"><h3>Privégegevens (versleuteld)</h3></div>'+field("Privé-e-mail","privateEmail",e.privateEmail,false,"email")+field("Privételefoon","privatePhone",e.privatePhone)+field("Adres","address",e.address)+field("Postcode","postalCode",e.postalCode)+field("Plaats","city",e.city)+field("Geboortedatum","birthDate",e.birthDate,false,"date")+
      '<div class="field full"><h3>Noodcontact (versleuteld)</h3></div>'+field("Naam noodcontact","emergencyContactName",e.emergencyContactName)+field("Relatie","emergencyContactRelation",e.emergencyContactRelation)+field("Telefoon noodcontact","emergencyContactPhone",e.emergencyContactPhone)+
      '</div></form>';
  }
  function field(label,name,value,required,type,extra) { return '<label class="field">'+esc(label)+'<input name="'+name+'" type="'+(type||"text")+'" value="'+esc(value==null?"":value)+'"'+(required?' required':'')+(extra||"")+'></label>'; }
  function detail(label,value) { return '<div><span>'+esc(label)+'</span><strong>'+esc(value||"-")+'</strong></div>'; }
  function renderEmployee() {
    var e=state.employee;if(!e)return; title.textContent=e.displayName; actions.innerHTML='<div class="button-row"><button data-action="employee-edit">Bewerken</button><button class="primary" data-action="contract-new">Contract toevoegen</button></div>';
    var content=state.tab==="contracts"?contractsTab(e):state.tab==="notes"?notesTab(e):state.tab==="audit"?auditTab():profileTab(e);
    app.innerHTML='<section class="card"><div class="detail-hero"><div><p class="eyebrow">'+esc(e.employeeNumber)+'</p><h2>'+esc(e.displayName)+'</h2><p class="muted">'+esc(e.jobTitle||"Geen functie")+' · '+esc(e.department||"Geen afdeling")+'</p></div>'+statusPill(e.status)+'</div><div class="tabs">'+tab("profile","Profiel")+tab("contracts","Contracten")+tab("notes","Notities")+tab("audit","Audit")+'</div>'+content+'</section>';
  }
  function tab(id,label){return '<button data-action="tab" data-tab="'+id+'" class="'+(state.tab===id?'active':'')+'">'+label+'</button>';}
  function profileTab(e){return '<div class="detail-list">'+detail("Werk-e-mail",e.workEmail)+detail("Werktelefoon",e.workPhone)+detail("Dienstverband",employmentType(e.employmentType))+detail("Uren per week",String(e.hoursPerWeek||0))+detail("Startdatum",date(e.startDate))+detail("Einddatum",date(e.endDate))+detail("Privé-e-mail",e.privateEmail)+detail("Privételefoon",e.privatePhone)+detail("Adres",[e.address,e.postalCode,e.city].filter(Boolean).join(", "))+detail("Geboortedatum",date(e.birthDate))+detail("Noodcontact",e.emergencyContactName)+detail("Telefoon noodcontact",e.emergencyContactPhone)+'</div><div class="button-row" style="margin-top:20px">'+(e.status!=="archived"?'<button data-action="archive">Archiveren</button>':'<button data-action="restore">Herstellen als actief</button><button class="danger" data-action="purge-show">Definitief wissen</button>')+'</div><div id="purge-box"></div>';}
  function contractsTab(e){var rows=e.contracts.length?e.contracts.map(function(c){return '<tr><td><strong>'+esc(c.title)+'</strong><br><span class="muted">'+esc(c.fileName)+' · '+formatBytes(c.size)+'</span></td><td>'+esc(employmentType(c.contractType))+'</td><td>'+date(c.startDate)+' – '+date(c.endDate)+'</td><td><span class="pill '+(c.scanStatus==="clean"?'ok':'warn')+'">'+esc(c.scanStatus==="clean"?"Veilig":"Quarantaine")+'</span></td><td><div class="button-row">'+(c.scanStatus==="clean"?'<button data-action="contract-download" data-id="'+c.id+'">Download</button>':'<button data-action="contract-rescan" data-id="'+c.id+'">Opnieuw scannen</button>')+'<button data-action="contract-archive" data-id="'+c.id+'">Archiveer</button></div></td></tr>';}).join(""):'<tr><td colspan="5"><div class="empty">Nog geen contracten.</div></td></tr>';return '<div class="table-wrap"><table class="data-table"><thead><tr><th>Contract</th><th>Type</th><th>Looptijd</th><th>Scan</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div><div id="contract-form"></div>';}
  function notesTab(e){var notes=e.notes.length?'<div class="timeline">'+e.notes.map(function(n){return '<article><span class="pill">'+esc(n.category)+'</span><p>'+esc(n.body)+'</p><small class="muted">'+esc(n.updatedBy||n.createdBy)+' · '+date(String(n.updatedAt).slice(0,10))+'</small><div class="button-row"><button data-action="note-edit" data-id="'+n.id+'">Bewerk</button><button data-action="note-delete" data-id="'+n.id+'">Verwijder</button></div></article>';}).join("")+'</div>':'<div class="empty">Nog geen interne notities.</div>';return '<form data-form="note" class="card" style="box-shadow:none;margin-bottom:18px"><div class="field-grid"><label class="field">Categorie<select name="category">'+options([["general","Algemeen"],["performance","Functioneren"],["agreement","Afspraak"],["absence","Afwezigheid"],["other","Overig"]],"general")+'</select></label><label class="field full">Notitie<textarea name="body" rows="4" required></textarea></label></div><button class="primary">Notitie toevoegen</button></form>'+notes;}
  function auditTab(){return state.audit.length?'<div class="timeline">'+state.audit.map(function(a){return '<article><strong>'+esc(a.action)+'</strong><p class="muted">'+esc(a.actor)+' · '+new Date(a.createdAt).toLocaleString("nl-NL")+'</p></article>';}).join("")+'</div>':'<div class="empty">Geen auditregels gevonden.</div>';}
  function formatBytes(n){return n>1048576?(n/1048576).toFixed(1)+" MB":Math.ceil(n/1024)+" KB";}

  function loadDashboard(){return api("/api/hr/dashboard").then(function(d){state.dashboard=d;renderDashboard();});}
  function loadEmployees(params){params=params||{};var q=new URLSearchParams(params);return api("/api/hr/employees?"+q).then(function(p){state.employees=p.items;state.total=p.total;renderEmployees();});}
  function loadEmployee(id){return Promise.all([api("/api/hr/employees/"+encodeURIComponent(id)),api("/api/hr/employees/"+encodeURIComponent(id)+"/audit")]).then(function(r){state.employee=r[0].item;state.audit=r[1].items;renderEmployee();});}
  function renderRoute(){showApp();var r=route();document.querySelectorAll("[data-nav]").forEach(function(a){a.classList.toggle("active",r.indexOf(a.dataset.nav)===0);});if(r==="dashboard")return loadDashboard();if(r==="employees")return loadEmployees();if(r==="employee-new")return employeeForm();if(r.indexOf("employee-edit:")===0)return loadEmployee(r.split(":")[1]).then(function(){employeeForm(state.employee);});if(r.indexOf("employee:")===0)return loadEmployee(r.split(":")[1]);navigate("dashboard");}
  function formData(form){return Object.fromEntries(new FormData(form).entries());}
  function contractForm(){document.getElementById("contract-form").innerHTML='<form class="card" data-form="contract" style="box-shadow:none;margin-top:18px"><h3>Contract uploaden</h3><div class="field-grid">'+field("Titel","title","",true)+ '<label class="field">Type<select name="contractType">'+options([["permanent","Vast"],["temporary","Tijdelijk"],["on_call","Oproep"],["contractor","Inhuur"],["intern","Stage"]],"permanent")+'</select></label>'+field("Startdatum","startDate","",true,"date")+field("Einddatum","endDate","",false,"date")+field("Uren per week","hoursPerWeek","",false,"number",' min="0" max="80" step="0.5"')+'<label class="field">PDF (max. 8 MB)<input name="file" type="file" accept="application/pdf,.pdf" required></label><label class="field full">Omschrijving<textarea name="description" rows="3"></textarea></label></div><div class="button-row"><button class="primary">Upload en scan</button><button type="button" data-action="contract-cancel">Annuleren</button></div></form>';}
  function purgeForm(){document.getElementById("purge-box").innerHTML='<form class="notice danger" data-form="purge" style="margin-top:18px"><h3>Definitief en onomkeerbaar wissen</h3><p>Voer personeelsnummer <strong>'+esc(state.employee.employeeNumber)+'</strong>, uw wachtwoord en een nieuwe authenticatorcode in.</p><div class="field-grid">'+field("Personeelsnummer","confirmEmployeeNumber","",true)+field("Wachtwoord","password","",true,"password")+field("Authenticatorcode","code","",true)+'</div><button class="danger">Dossier definitief wissen</button></form>';}

  document.addEventListener("submit",function(event){var form=event.target.closest("form");if(!form)return;event.preventDefault();var button=form.querySelector("button[type=submit],button:not([type])");if(button)button.disabled=true;var work;
    if(form.dataset.form==="mfa-start")work=api("/api/hr/mfa/setup/start",{method:"POST",body:formData(form)}).then(setupConfirm);
    if(form.dataset.form==="mfa-confirm")work=api("/api/hr/mfa/setup/confirm",{method:"POST",body:formData(form)}).then(function(p){recoveryGate(p.recoveryCodes);});
    if(form.dataset.form==="elevate")work=api("/api/hr/elevate",{method:"POST",body:formData(form)}).then(renderRoute);
    if(form.dataset.form==="employee"){var id=form.dataset.id;work=api("/api/hr/employees"+(id?"/"+id:""),{method:id?"PUT":"POST",body:formData(form)}).then(function(p){toast("Werknemer opgeslagen.");navigate("employee:"+p.item.id);});}
    if(form.dataset.form==="contract"){var fd=new FormData(form);work=api("/api/hr/employees/"+state.employee.id+"/contracts",{method:"POST",body:fd}).then(function(p){toast(p.item.scanStatus==="clean"?"Contract veilig toegevoegd.":"Contract staat in quarantaine.");return loadEmployee(state.employee.id);});}
    if(form.dataset.form==="note"){work=api("/api/hr/employees/"+state.employee.id+"/notes",{method:"POST",body:formData(form)}).then(function(){toast("Notitie toegevoegd.");return loadEmployee(state.employee.id);});}
    if(form.dataset.form==="purge"){if(!confirm("Dit dossier en alle contracten definitief wissen?"))work=Promise.resolve();else work=api("/api/hr/employees/"+state.employee.id+"/purge",{method:"POST",body:formData(form)}).then(function(){toast("Dossier definitief gewist.");navigate("employees");});}
    Promise.resolve(work).catch(function(e){toast(e.message);if(e.code==="HR_ELEVATION_REQUIRED")elevateGate();}).finally(function(){if(button)button.disabled=false;});
  });
  document.addEventListener("click",function(event){var target=event.target.closest("[data-action],[data-open]");if(!target)return;var action=target.dataset.action;if(target.dataset.open)return navigate(target.dataset.open);if(action==="recovery-done")return elevateGate();if(action==="employee-new")return navigate("employee-new");if(action==="cancel-employee")return navigate(state.employee?"employee:"+state.employee.id:"employees");if(action==="employee-edit")return navigate("employee-edit:"+state.employee.id);if(action==="contract-new"){state.tab="contracts";renderEmployee();return contractForm();}if(action==="contract-cancel")return renderEmployee();if(action==="purge-show")return purgeForm();if(action==="tab"){state.tab=target.dataset.tab;if(state.tab==="audit")return loadEmployee(state.employee.id);return renderEmployee();}
    if(action==="archive"||action==="restore"){var data=Object.assign({},state.employee,{status:action==="archive"?"archived":"active"});if(action==="archive"&&!confirm("Werknemer archiveren?"))return;return api("/api/hr/employees/"+state.employee.id,{method:"PUT",body:data}).then(function(){toast("Status bijgewerkt.");return loadEmployee(state.employee.id);}).catch(function(e){toast(e.message);});}
    if(action==="contract-rescan")return api("/api/hr/employees/"+state.employee.id+"/contracts/"+target.dataset.id+"/rescan",{method:"POST"}).then(function(){toast("Contract opnieuw gescand.");return loadEmployee(state.employee.id);}).catch(function(e){toast(e.message);});
    if(action==="contract-archive")return api("/api/hr/employees/"+state.employee.id+"/contracts/"+target.dataset.id,{method:"PATCH",body:{status:"archived"}}).then(function(){toast("Contract gearchiveerd.");return loadEmployee(state.employee.id);}).catch(function(e){toast(e.message);});
    if(action==="contract-download")return api("/api/hr/employees/"+state.employee.id+"/contracts/"+target.dataset.id+"/download",{binary:true}).then(function(blob){var url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="contract.pdf";a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}).catch(function(e){toast(e.message);});
    if(action==="note-delete"){if(!confirm("Notitie verwijderen?"))return;return api("/api/hr/employees/"+state.employee.id+"/notes/"+target.dataset.id,{method:"DELETE"}).then(function(){toast("Notitie verwijderd.");return loadEmployee(state.employee.id);}).catch(function(e){toast(e.message);});}
    if(action==="note-edit"){var note=state.employee.notes.find(function(n){return n.id===target.dataset.id;}),body=prompt("Notitie bewerken",note.body);if(body===null)return;return api("/api/hr/employees/"+state.employee.id+"/notes/"+note.id,{method:"PUT",body:{category:note.category,body:body}}).then(function(){toast("Notitie bijgewerkt.");return loadEmployee(state.employee.id);}).catch(function(e){toast(e.message);});}
    if(action==="employee-filter"){var search=document.querySelector('[data-filter="search"]').value,status=document.querySelector('[data-filter="status"]').value;return loadEmployees({search:search,status:status});}
    if(action==="lock")return api("/api/hr/lock",{method:"POST"}).then(elevateGate).catch(function(e){toast(e.message);});
  });
  window.addEventListener("hashchange",function(){renderRoute().catch(function(e){if(e.code==="HR_ELEVATION_REQUIRED")elevateGate();else toast(e.message);});});
  document.addEventListener("click", function (event) {
    if (event.target.closest('[data-action="recovery-finished"]')) renderRoute().catch(function (error) { toast(error.message); });
    if (event.target.closest('[data-action="employee-filter-all"]')) {
      var params = {};
      document.querySelectorAll("[data-filter]").forEach(function (field) { params[field.dataset.filter] = field.value; });
      loadEmployees(params).catch(function (error) { toast(error.message); });
    }
  });
  api("/api/auth/session").then(function(session){csrf=session.csrfToken||"";if(!session.authenticated||!session.user||session.user.role!=="admin")throw new Error("Geen beheerderstoegang.");return api("/api/hr/session");}).then(function(hrSession){if(!hrSession.mfaEnabled)return setupGate();if(!hrSession.elevated)return elevateGate();return renderRoute();}).catch(function(e){showGate('<h1>Geen toegang</h1><p>'+esc(e.message)+'</p><p><a href="/">Terug naar CRM</a></p>');});
}());
